### ISSUE TITLE
Public holiday API doesn't give data for next year

### ISSUE THREAD

**Issue by davidRoussov** [davidRoussov/trade-up#2]
I think the data is just for this year and the previous year. This can be an issue if someone clicks the next or previous buttons many times - those public holidays won't be highlighted on the calendar. 

There also may be some problems with the API data accuracy that needs to be investigated...

**Comment by Jasonluo666** [comment]
Try this "date-holidays":
[https://www.npmjs.com/package/date-holidays#supported-countries-states-regions](url)
